# ==Forvo Command-Line Lookup Tool Configuration File==
#
# By default, gdcl will look for this file in the config folder under the
# user's home directory (~/.config/forvocl/) or in the $XDG_CONFIG_DIRS 
# (/etc/xdg/forvocl). If it can't find a file named config.yml in these default 
# location, it will look for it in the current working directory. If 
# config.yml cannot be found in any of the above locations, the program will 
# abort with an error message explaining the situation.


# ==Configuration options==

# forvo key
# this key should be set in the user config file only
# :forvo_key: ""
